---
title: "Ranking the predictions"
author: "Xijin Ge & STAT442 students 2022"
date: "2022-10-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

```


```{r}
library(readr)
rent <- read_csv("student_predictions.csv", 
col_types = cols(
  `Posted On` = col_date(format = "%m/%d/%Y"),
  Size = col_integer(), 
  Unit.Floor = col_integer(), 
  Total.Floors = col_integer()
  )
)
colnames(rent)
```

```{r}
predictions <- rent[, -(1:13)]
head(predictions)
```

```{r}
summary(predictions)
```


#  Missing value imputation
```{r}
library(dplyr)
median_rent <- median(rent$Rent)

predictions <- predictions %>%
  mutate(
    Lucas = ifelse(
      Lucas < 0,
      median_rent,
      Lucas
    )
  ) %>%
  mutate(
    Bethany = ifelse(
      Bethany < 1,
      median_rent,
      Bethany
    )
  ) %>%
  mutate(
    Hannah = ifelse(
      Hannah < 1,
      median_rent,
      Hannah
    )
  ) 

summary(predictions)
```


# Calculating RMSE

```{r}
library(Metrics)
actual_rent_log <- log10(rent$Rent)
predictions <- log10(as.matrix(predictions))

RMSEs <- apply(
  predictions, 
  MARGIN = 2, 
  FUN = function(x) { 
    Metrics::rmse(actual_rent_log, x) 
  }
)

RMSE <- round(sort(RMSEs), 4)
```


```{r}
df <- as.data.frame(RMSE)
df$name <- names(RMSE)

# preserve the order in plot
df$name <- factor(df$name, levels = rev(df$name))
library(ggplot2)
ggplot(df, aes(x = name, y = RMSE)) +
  geom_segment(
    aes(x = name, xend = name, y = 0, yend = RMSE), 
    color = "gray", 
    lwd = 2
  ) +
  geom_point(
    size = 4,
    pch = 21, 
    bg = "red", 
    col = "red"
  ) +
  geom_text(
    aes(label = RMSE), 
    color = "blue", 
    size = 3, 
    nudge_y = .02
  ) +
  theme(
    axis.text.x=element_blank(),
    axis.ticks.x=element_blank(),
    axis.title.y = element_blank()
  )+
  coord_flip()
```

## Marie's model
```{r, eval = FALSE}
library(mgcv)
library(nlme)

gen.am <- gam(
  logRent ~ s(logSize,k=11) + City + Furnishing.Status + Bathroom 
    + BHK + Area.Type + Point.of.Contact +Total.Floors, 
  data = rent.practice
)
gen.am
#R-sq.(adj) =  0.821 
```


## Hannah's model
```{r, eval = FALSE}
fit2 <- lm(logrent ~ BHK + Size + City + `Furnishing Status` 
           + Bathroom  +`Point of Contact`, 
           data = rent2
)
summary(fit2)
#Adjusted R-squared:  0.8099 
```


## Emma's model
```{r, eval = FALSE}
model <- lm(Log.Rent ~ City + BHK + Size + Tenant.Preferred + 
              Furnishing.Status + Point.of.Contact + Num.Floors, 
           data = rent5)
#Adjusted R-squared:  0.8119 
```



## Jacob's model
```{r, eval = FALSE}
lm <- lm(rent.log$Rent ~ rent.log[, 2] + rent.log[, 3] + 
           rent.log[, 7] + rent.log[, 8] + rent.log[, 11])

#Size + City + BHK + Contact + Furnishing Status  ???
# Adjusted R-squred: 0.8056	
```






#  Ensemble approach (many models vote)
```{r}
predictions_subset <- subset(
  predictions,
  select = c(Marie, Hannah, Emma, Jacob)
)
                      
ensembl_prediction <- apply(
  predictions_subset,
  MARGIN = 1,
  FUN = mean
)
Metrics::rmse(actual_rent_log, ensembl_prediction)
```

```{r}
library(corrplot)
df <- cbind(predictions, rent = actual_rent_log)
corrplot.mixed(cor(df), order = "AOE")
```

```{r}
dist_pearson <- function(x, ...)
  as.dist(1-cor(t(x), method="pearson"))
plot(
  hclust(
    dist_pearson(t(df)),
    method = "average"
  ),
  xlab = NULL
)
```

```{r}
library(reshape2)
wide_data = cbind(t(df), names = colnames(df))
long_data <- melt(wide_data, id.vars = c("names") )
colnames(long_data)[1] = "name"
head(long_data)
long_data$value <- as.numeric(long_data$value)

ggplot(long_data, aes(x=name, y=value, color = name, fill = name)) +
  geom_violin(trim=FALSE, show.legend = FALSE) 
```

```{r}
ggplot(long_data, aes(x=name, y=value, color = name, fill = name)) +
  geom_violin(trim=FALSE, show.legend = FALSE) +
  ylim(3.5, 6)
```

## Factors


| Factors     | Marie | Hannah | Emma   | Jacob5  | Jacob6  | Jacob7  |
| :--------: | :----:| :-----:| :-----:| :-----:| :-----:|:-----:|
| Size        |   O   |O       |O       |O       |O       |O       |
| City        |   O   |O       |O       |O       |O       |O       |
| Contact     |   O   |O       |O       |O       |O       |O       |
| BHK         |   O   |O       |O       |O       |O       |O       |
| Bathroom    |   O   |O       |-       |O       |O       |O       |
| Furnishing  |   O   |O       |O       |-       |O       |O       |
| Total.Floors|   O   |-       |O       |-       |-       |O       |
| Area.Type   |   O   |-       |-       |-       |-       |-       |
| Tenant      |   -   |-       |O       |-       |-       |-       |


```{r}
data_all <- cbind(
  rent[, 1:12], 
  Rent = log10(rent$Rent), 
  predictions
)
#write.csv(data_all, "model_performance.csv", row.names = FALSE)
```


```{r}
  ggplot(data_all,
         aes(
           x = Rent,
           y = Marie,
           color = City
         )) +
    geom_point() +
    xlim(3.4, 5.7) +
    ylim(3.4, 5.7) +
    xlab("Actual Rent (log10)") + 
    geom_abline(intercept = 0, slope = 1, size = 0.5)

```


```{r}
  library(plotly)
  p <- ggplot(data_all,
         aes(
           x = Rent,
           y = Marie,
           color = City
         )) +
    geom_point() +
    xlim(3.4, 5.7) +
    ylim(3.4, 5.7) +
    xlab("Actual Rent (log10)") + 
    geom_abline(intercept = 0, slope = 1, size = 0.5)
  
  ggplotly(p)

```
